// <auto-generated />
using Nhom6_QuanLyTourDuLich_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Nhom6_QuanLyTourDuLich_BackEnd.Migrations
{
    [DbContext(typeof(QuanLyTourDuLich_DBContext))]
    [Migration("20230910101306_DBInitialTinhHuyenXa")]
    partial class DBInitialTinhHuyenXa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.HuyenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("maTinh");

                    b.HasIndex("tenHuyen")
                        .IsUnique();

                    b.ToTable("Huyen", (string)null);
                });

            modelBuilder.Entity("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.TinhEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("tenTinh")
                        .IsUnique();

                    b.ToTable("Tinh", (string)null);
                });

            modelBuilder.Entity("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.XaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("maHuyen");

                    b.HasIndex("tenXa")
                        .IsUnique();

                    b.ToTable("Xa", (string)null);
                });

            modelBuilder.Entity("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.HuyenEntity", b =>
                {
                    b.HasOne("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.TinhEntity", "Tinh")
                        .WithMany("Huyens")
                        .HasForeignKey("maTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tinh");
                });

            modelBuilder.Entity("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.XaEntity", b =>
                {
                    b.HasOne("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.HuyenEntity", "Huyen")
                        .WithMany("Xas")
                        .HasForeignKey("maHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Huyen");
                });

            modelBuilder.Entity("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.HuyenEntity", b =>
                {
                    b.Navigation("Xas");
                });

            modelBuilder.Entity("CongNghePhanMemNangCao_Nhom6_QuanLyTourDuLich.Data.TinhEntity", b =>
                {
                    b.Navigation("Huyens");
                });
#pragma warning restore 612, 618
        }
    }
}
