// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom6_QuanLyTourDuLich_BackEnd.Data;

#nullable disable

namespace Nhom6_QuanLyTourDuLich_BackEnd.Migrations
{
    [DbContext(typeof(QuanLyTourDuLich_DBContext))]
    [Migration("20230919173407_DB_AddTableTaiKhoanLoaiTaiKhoan")]
    partial class DB_AddTableTaiKhoanLoaiTaiKhoan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.HuyenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("maTinh");

                    b.HasIndex("tenHuyen")
                        .IsUnique();

                    b.ToTable("Huyen", (string)null);
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.LoaiTaiKhoanEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiTaiKhoanEntity");
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.TaiKhoanEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("maLoai");

                    b.HasIndex("soDienThoai")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.TinhEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("tenTinh")
                        .IsUnique();

                    b.ToTable("Tinh", (string)null);
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.XaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("maHuyen");

                    b.HasIndex("tenXa")
                        .IsUnique();

                    b.ToTable("Xa", (string)null);
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.HuyenEntity", b =>
                {
                    b.HasOne("Nhom6_QuanLyTourDuLich_BackEnd.Data.TinhEntity", "Tinh")
                        .WithMany("Huyens")
                        .HasForeignKey("maTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tinh");
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.TaiKhoanEntity", b =>
                {
                    b.HasOne("Nhom6_QuanLyTourDuLich_BackEnd.Data.LoaiTaiKhoanEntity", "LoaiTaiKhoan")
                        .WithMany()
                        .HasForeignKey("maLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTaiKhoan");
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.XaEntity", b =>
                {
                    b.HasOne("Nhom6_QuanLyTourDuLich_BackEnd.Data.HuyenEntity", "Huyen")
                        .WithMany("Xas")
                        .HasForeignKey("maHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Huyen");
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.HuyenEntity", b =>
                {
                    b.Navigation("Xas");
                });

            modelBuilder.Entity("Nhom6_QuanLyTourDuLich_BackEnd.Data.TinhEntity", b =>
                {
                    b.Navigation("Huyens");
                });
#pragma warning restore 612, 618
        }
    }
}
